"use client";
import { FormEvent, useEffect, useState } from "react";
import type { Session } from "@supabase/supabase-js";
import { supabase } from "@/lib/supabase";
import { AcademyAccessProvider, type AcademyRole } from "./AcademyAccess";

type Member = { display_name: string; role: AcademyRole; active: boolean };
export default function AuthGate({ children }: { children: React.ReactNode }) {
  const [session, setSession] = useState<Session | null>(null); const [member, setMember] = useState<Member | null>(null); const [checking, setChecking] = useState(true);
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [submitting, setSubmitting] = useState(false);
  useEffect(() => { let mounted = true; const resolve = async (next: Session | null) => { if (!mounted) return; setSession(next); if (!next) { setMember(null); setChecking(false); return; } const { data, error: memberError } = await supabase.from("academy_users").select("display_name,role,active").eq("user_id", next.user.id).single(); if (!mounted) return; if (memberError || !data?.active) { setError("사용 권한이 없는 계정입니다. 원장님께 문의해 주세요."); setMember(null); await supabase.auth.signOut(); } else setMember(data as Member); setChecking(false); }; void supabase.auth.getSession().then(({ data }) => resolve(data.session)); const { data: listener } = supabase.auth.onAuthStateChange((_event, next) => { setChecking(true); void resolve(next); }); return () => { mounted = false; listener.subscription.unsubscribe(); }; }, []);
  const login = async (event: FormEvent) => { event.preventDefault(); setSubmitting(true); setError(""); const { error: loginError } = await supabase.auth.signInWithPassword({ email: email.trim(), password }); setSubmitting(false); if (loginError) setError("이메일 또는 비밀번호를 확인해 주세요."); };
  if (checking) return <div className="flex min-h-screen items-center justify-center bg-emerald-50 text-sm font-semibold text-emerald-700">로그인과 권한을 확인하는 중...</div>;
  if (!session || !member) return <main className="flex min-h-screen items-center justify-center bg-gradient-to-b from-emerald-50 to-white px-5 py-12"><div className="w-full max-w-sm rounded-3xl bg-white p-7 shadow-xl ring-1 ring-emerald-100 sm:p-9"><div className="text-center"><div className="mx-auto flex h-16 w-16 items-center justify-center rounded-2xl bg-emerald-100 text-3xl">🎨</div><p className="mt-5 text-sm font-bold text-emerald-600">COCO ART ACADEMY</p><h1 className="mt-1 text-2xl font-bold">코코미술학원 AI</h1><p className="mt-2 text-sm text-zinc-500">원장·강사 전용 관리 화면입니다.</p></div><form onSubmit={login} className="mt-7 grid gap-4"><label className="grid gap-1.5 text-sm font-semibold">이메일<input required type="email" autoComplete="email" value={email} onChange={(e) => setEmail(e.target.value)} className="rounded-xl border px-4 py-3.5 font-normal" /></label><label className="grid gap-1.5 text-sm font-semibold">비밀번호<input required type="password" autoComplete="current-password" value={password} onChange={(e) => setPassword(e.target.value)} className="rounded-xl border px-4 py-3.5 font-normal" /></label>{error && <p className="rounded-xl bg-red-50 px-3 py-2.5 text-sm text-red-700">{error}</p>}<button disabled={submitting} className="rounded-xl bg-emerald-600 py-4 font-bold text-white disabled:opacity-50">{submitting ? "로그인 중..." : "로그인"}</button></form></div></main>;
  return <AcademyAccessProvider value={{ role: member.role, displayName: member.display_name }}>{children}</AcademyAccessProvider>;
}
