"use client";
import { FormEvent, useEffect, useState } from "react";
import type { Session } from "@supabase/supabase-js";
import { supabase } from "@/lib/supabase";
import { AcademyAccessProvider, type AcademyRole } from "./AcademyAccess";

type Member={display_name:string;role:AcademyRole;active:boolean;approval_status?:string};
export default function AuthGate({children}:{children:React.ReactNode}){
 const [session,setSession]=useState<Session|null>(null),[member,setMember]=useState<Member|null>(null),[checking,setChecking]=useState(true),[mode,setMode]=useState<"login"|"signup"|"recovery">("login"),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[name,setName]=useState(""),[error,setError]=useState(""),[notice,setNotice]=useState(""),[submitting,setSubmitting]=useState(false);
 useEffect(()=>{let mounted=true;const resolve=async(next:Session|null,event?:string)=>{if(!mounted)return;setSession(next);if(event==="PASSWORD_RECOVERY"){setMode("recovery");setChecking(false);return}if(!next){setMember(null);setChecking(false);return}const {data,error:memberError}=await supabase.from("academy_users").select("display_name,role,active,approval_status").eq("user_id",next.user.id).single();if(!mounted)return;if(memberError||!data?.active){const status=data?.approval_status;setError(status==="rejected"?"가입 신청이 승인되지 않았습니다. 원장님께 문의해 주세요.":"원장님의 승인을 기다리고 있는 계정입니다.");setMember(null);await supabase.auth.signOut()}else setMember(data as Member);setChecking(false)};void supabase.auth.getSession().then(({data})=>resolve(data.session));const {data:listener}=supabase.auth.onAuthStateChange((event,next)=>{setChecking(true);void resolve(next,event)});return()=>{mounted=false;listener.subscription.unsubscribe()}},[]);
 const submit=async(e:FormEvent)=>{e.preventDefault();setSubmitting(true);setError("");setNotice("");if(mode==="signup"){const {error:signupError}=await supabase.auth.signUp({email:email.trim(),password,options:{data:{name:name.trim()},emailRedirectTo:window.location.origin}});if(signupError)setError(signupError.message);else{setNotice("가입 신청을 보냈습니다. 이메일 확인 후 원장님의 승인을 기다려 주세요.");setMode("login")}}else if(mode==="recovery"){const {error:updateError}=await supabase.auth.updateUser({password});if(updateError)setError(updateError.message);else{setNotice("새 비밀번호로 변경했습니다.");setMode("login");await supabase.auth.signOut()}}else{const {error:loginError}=await supabase.auth.signInWithPassword({email:email.trim(),password});if(loginError)setError("이메일 또는 비밀번호를 확인해 주세요.")}setSubmitting(false)};
 if(checking)return <div className="flex min-h-screen items-center justify-center bg-emerald-50 text-sm font-semibold text-emerald-700">로그인과 권한을 확인하는 중...</div>;
 if(session&&member)return <AcademyAccessProvider value={{role:member.role,displayName:member.display_name}}>{children}</AcademyAccessProvider>;
 return <main className="flex min-h-screen items-center justify-center bg-gradient-to-b from-emerald-50 to-white px-5 py-12"><div className="w-full max-w-sm rounded-3xl bg-white p-7 shadow-xl ring-1 ring-emerald-100"><div className="text-center"><div className="mx-auto flex h-16 w-16 items-center justify-center rounded-2xl bg-emerald-100 text-3xl">🎨</div><p className="mt-5 text-sm font-bold text-emerald-600">COCO ART ACADEMY</p><h1 className="mt-1 text-2xl font-bold">{mode==="signup"?"강사 가입 신청":mode==="recovery"?"새 비밀번호 설정":"코코미술학원 AI"}</h1><p className="mt-2 text-sm text-zinc-500">{mode==="signup"?"신청 후 원장님의 승인이 필요합니다.":mode==="recovery"?"앞으로 사용할 비밀번호를 입력하세요.":"원장·강사 전용 관리 화면입니다."}</p></div><form onSubmit={submit} className="mt-7 grid gap-4">{mode==="signup"&&<label className="grid gap-1.5 text-sm font-semibold">강사 이름<input required value={name} onChange={e=>setName(e.target.value)} className="rounded-xl border px-4 py-3.5 font-normal" /></label>}{mode!=="recovery"&&<label className="grid gap-1.5 text-sm font-semibold">이메일<input required type="email" value={email} onChange={e=>setEmail(e.target.value)} className="rounded-xl border px-4 py-3.5 font-normal" /></label>}<label className="grid gap-1.5 text-sm font-semibold">{mode==="recovery"?"새 비밀번호":"비밀번호"}<input required minLength={8} type="password" value={password} onChange={e=>setPassword(e.target.value)} className="rounded-xl border px-4 py-3.5 font-normal" /></label>{error&&<p className="rounded-xl bg-red-50 px-3 py-2.5 text-sm text-red-700">{error}</p>}{notice&&<p className="rounded-xl bg-emerald-50 px-3 py-2.5 text-sm text-emerald-700">{notice}</p>}<button disabled={submitting} className="rounded-xl bg-emerald-600 py-4 font-bold text-white disabled:opacity-50">{submitting?"처리 중...":mode==="signup"?"가입 신청":mode==="recovery"?"비밀번호 변경":"로그인"}</button></form>{mode!=="recovery"&&<button onClick={()=>{setMode(mode==="login"?"signup":"login");setError("");setNotice("")}} className="mt-5 w-full text-sm font-bold text-emerald-700">{mode==="login"?"강사 가입 신청하기":"로그인으로 돌아가기"}</button>}</div></main>
}
