"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { supabase } from "@/lib/supabase";

type Tab = "ledger"|"year"|"overdue";
type Transaction = {id:string;transaction_date:string;transaction_type:"income"|"expense";category:string;description:string;payment_method:string;amount:number};
type Student = {id:string;name:string};
type Enrollment = {id:string;student_id:string;monthly_fee:number};
type TuitionPayment = {id:string;student_id:string;billing_month:string;amount:number;paid:boolean;paid_at:string|null};
type TransactionForm = {transaction_date:string;transaction_type:"income"|"expense";category:string;description:string;payment_method:string;amount:string};

const won=(value:number)=>`${value.toLocaleString("ko-KR")}원`;
const today=()=>new Date().toLocaleDateString("sv-SE");
const currentMonth=()=>today().slice(0,7);
const emptyTransaction:TransactionForm={transaction_date:today(),transaction_type:"expense",category:"재료비",description:"",payment_method:"card",amount:""};
const categoryOptions={income:["원비","특강비","재료비 수입","기타 수입"],expense:["재료비","임대료","공과금","차량비","인건비","기타 지출"]};
const methodLabel:Record<string,string>={card:"카드",cash:"현금",transfer:"계좌이체",other:"기타"};

function Modal({onClose,children}:{onClose:()=>void;children:React.ReactNode}){return <div className="fixed inset-0 z-50 flex items-end justify-center bg-black/40 sm:items-center sm:p-4"><div className="max-h-[94vh] w-full max-w-lg overflow-y-auto rounded-t-3xl bg-white p-6 shadow-2xl sm:rounded-3xl"><div className="mb-5 flex items-center justify-between"><h2 className="text-xl font-bold">수입·지출 등록</h2><button type="button" onClick={onClose} className="rounded-full bg-zinc-100 px-3 py-1.5 text-sm">닫기</button></div>{children}</div></div>}

export default function FinancePage(){
  const [tab,setTab]=useState<Tab>("ledger"); const [month,setMonth]=useState(currentMonth());
  const [transactions,setTransactions]=useState<Transaction[]>([]); const [students,setStudents]=useState<Student[]>([]);
  const [enrollments,setEnrollments]=useState<Enrollment[]>([]); const [payments,setPayments]=useState<TuitionPayment[]>([]);
  const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState(""); const [notice,setNotice]=useState("");
  const [modal,setModal]=useState(false); const [form,setForm]=useState(emptyTransaction);

  const load=useCallback(async()=>{setLoading(true);setError("");const results=await Promise.all([
    supabase.from("finance_transactions").select("*").order("transaction_date",{ascending:false}),
    supabase.from("students").select("id,name").eq("active",true).order("name"),
    supabase.from("class_enrollments").select("id,student_id,monthly_fee"),
    supabase.from("tuition_payments").select("*").order("billing_month",{ascending:false}),
  ]);const failed=results.find(result=>result.error)?.error;if(failed)setError(failed.code==="PGRST205"||failed.code==="42703"?"재무 관리 데이터베이스 설정이 필요합니다.":failed.message);else{setTransactions(results[0].data as Transaction[]);setStudents(results[1].data as Student[]);setEnrollments(results[2].data as Enrollment[]);setPayments(results[3].data as TuitionPayment[])}setLoading(false)},[]);
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[load]);
  const flash=(message:string)=>{setNotice(message);window.setTimeout(()=>setNotice(""),2500)};
  const monthDate=`${month}-01`; const monthTransactions=transactions.filter(item=>item.transaction_date.startsWith(month)); const monthPayments=payments.filter(item=>item.billing_month===monthDate&&item.paid);
  const income=monthTransactions.filter(item=>item.transaction_type==="income").reduce((sum,item)=>sum+item.amount,0)+monthPayments.reduce((sum,item)=>sum+item.amount,0);
  const expense=monthTransactions.filter(item=>item.transaction_type==="expense").reduce((sum,item)=>sum+item.amount,0); const net=income-expense;
  const feeStudents=students.map(student=>({student,enrollment:enrollments.find(item=>item.student_id===student.id),payment:payments.find(item=>item.student_id===student.id&&item.billing_month===monthDate)})).filter(item=>(item.enrollment?.monthly_fee??0)>0);
  const overdue=feeStudents.filter(item=>!item.payment?.paid); const overdueTotal=overdue.reduce((sum,item)=>sum+(item.enrollment?.monthly_fee??0),0);
  const year=Number(month.slice(0,4)); const yearRows=useMemo(()=>Array.from({length:12},(_,index)=>{const key=`${year}-${String(index+1).padStart(2,"0")}`;const tx=transactions.filter(item=>item.transaction_date.startsWith(key));const paid=payments.filter(item=>item.billing_month===`${key}-01`&&item.paid);const inc=tx.filter(item=>item.transaction_type==="income").reduce((sum,item)=>sum+item.amount,0)+paid.reduce((sum,item)=>sum+item.amount,0);const out=tx.filter(item=>item.transaction_type==="expense").reduce((sum,item)=>sum+item.amount,0);return {month:index+1,income:inc,expense:out,net:inc-out}}),[payments,transactions,year]);

  const saveTransaction=async(event:FormEvent)=>{event.preventDefault();setSaving(true);const {error:saveError}=await supabase.from("finance_transactions").insert({...form,amount:Number(form.amount)});setSaving(false);if(saveError)return setError(saveError.message);setModal(false);setForm({...emptyTransaction,transaction_date:today()});flash("내역을 저장했습니다.");await load()};
  const deleteTransaction=async(id:string)=>{if(!window.confirm("이 내역을 삭제할까요?"))return;const {error:deleteError}=await supabase.from("finance_transactions").delete().eq("id",id);if(deleteError)return setError(deleteError.message);flash("내역을 삭제했습니다.");await load()};
  const updateFee=async(enrollment:Enrollment,value:number)=>{const {error:updateError}=await supabase.from("class_enrollments").update({monthly_fee:value}).eq("id",enrollment.id);if(updateError)return setError(updateError.message);setEnrollments(current=>current.map(item=>item.id===enrollment.id?{...item,monthly_fee:value}:item));flash("월 원비를 저장했습니다.")};
  const togglePaid=async(student:Student,enrollment:Enrollment,payment?:TuitionPayment)=>{setSaving(true);const paid=!payment?.paid;const {error:paymentError}=await supabase.from("tuition_payments").upsert({student_id:student.id,billing_month:monthDate,amount:enrollment.monthly_fee,paid,paid_at:paid?new Date().toISOString():null},{onConflict:"student_id,billing_month"});setSaving(false);if(paymentError)return setError(paymentError.message);flash(paid?`${student.name} 원비를 납부 처리했습니다.`:`${student.name} 원비를 미납으로 변경했습니다.`);await load()};

  return <main className="min-h-screen flex-1 bg-[#f8f4ed] px-3 py-6 sm:px-6"><div className="mx-auto max-w-7xl"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-bold tracking-[.25em] text-rose-700">FINANCE</p><h1 className="mt-2 text-3xl font-bold text-zinc-900">재무 관리</h1><p className="mt-2 text-sm text-zinc-500">월별 장부와 연간 현황, 학생 원비 납부를 한곳에서 관리합니다.</p></div><button type="button" onClick={()=>setModal(true)} className="rounded-2xl bg-rose-700 px-5 py-3 font-bold text-white shadow-lg shadow-rose-200">+ 내역 등록</button></header>
  {notice&&<div className="mt-4 rounded-xl bg-emerald-600 px-4 py-3 text-sm font-bold text-white">{notice}</div>}{error&&<div className="mt-4 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}
  <div className="mt-6 flex flex-wrap items-center justify-between gap-3"><nav className="flex rounded-2xl bg-[#eadfd3] p-1.5">{([['ledger','월별 장부'],['year','1년 현황'],['overdue','미납 관리']] as [Tab,string][]).map(([key,label])=><button key={key} onClick={()=>setTab(key)} className={`rounded-xl px-4 py-2.5 text-sm font-bold ${tab===key?'bg-white text-rose-700 shadow-sm':'text-zinc-600'}`}>{label}</button>)}</nav><input type="month" value={month} onChange={event=>setMonth(event.target.value)} className="rounded-xl border border-[#dfd3c7] bg-white px-4 py-3 font-bold"/></div>
  {loading?<div className="mt-5 rounded-2xl bg-white p-12 text-center">불러오는 중...</div>:<>
  <section className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><div className="rounded-2xl border border-[#e7ddd3] bg-white p-5"><p className="text-sm text-zinc-500">이번 달 수입</p><p className="mt-3 text-2xl font-bold">{won(income)}</p></div><div className="rounded-2xl border border-[#e7ddd3] bg-white p-5"><p className="text-sm text-zinc-500">이번 달 지출</p><p className="mt-3 text-2xl font-bold">{won(expense)}</p></div><div className={`rounded-2xl p-5 text-white ${net>=0?'bg-emerald-800':'bg-[#552526]'}`}><p className="text-sm opacity-80">순이익</p><p className="mt-3 text-2xl font-bold">{won(net)}</p></div><button onClick={()=>setTab('overdue')} className="rounded-2xl border border-[#e7ddd3] bg-white p-5 text-left"><p className="text-sm text-zinc-500">미납금</p><p className="mt-3 text-2xl font-bold text-red-600">{won(overdueTotal)}</p><p className="mt-2 text-xs text-zinc-500">{overdue.length}명 미납</p></button></section>
  {tab==='ledger'&&<section className="mt-5 overflow-hidden rounded-2xl border border-[#e7ddd3] bg-white"><div className="p-5"><h2 className="text-xl font-bold">수입·지출 내역</h2><p className="mt-1 text-sm text-zinc-500">원비 납부 내역은 학생 관리와 자동 연결됩니다.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-sm"><thead className="bg-zinc-50 text-left text-xs text-zinc-500"><tr><th className="p-4">날짜</th><th className="p-4">구분</th><th className="p-4">내용</th><th className="p-4">결제</th><th className="p-4 text-right">금액</th><th className="p-4"/></tr></thead><tbody>{monthPayments.map(item=><tr key={`payment-${item.id}`} className="border-t"><td className="p-4">{month.slice(5)}월</td><td className="p-4 text-emerald-700">수입</td><td className="p-4 font-bold">{students.find(student=>student.id===item.student_id)?.name} 원비</td><td className="p-4">원비 납부</td><td className="p-4 text-right font-bold text-emerald-700">+ {won(item.amount)}</td><td/></tr>)}{monthTransactions.map(item=><tr key={item.id} className="border-t"><td className="p-4">{item.transaction_date.slice(5).replace('-','.')}</td><td className={`p-4 ${item.transaction_type==='income'?'text-emerald-700':'text-rose-600'}`}>{item.transaction_type==='income'?'수입':'지출'}</td><td className="p-4"><b>{item.description}</b><span className="ml-2 text-xs text-zinc-400">{item.category}</span></td><td className="p-4">{methodLabel[item.payment_method]}</td><td className={`p-4 text-right font-bold ${item.transaction_type==='income'?'text-emerald-700':'text-rose-600'}`}>{item.transaction_type==='income'?'+':'-'} {won(item.amount)}</td><td className="p-4"><button onClick={()=>void deleteTransaction(item.id)} className="text-xs text-zinc-400 hover:text-red-600">삭제</button></td></tr>)}{monthTransactions.length===0&&monthPayments.length===0&&<tr><td colSpan={6} className="p-10 text-center text-zinc-400">등록된 내역이 없습니다.</td></tr>}</tbody></table></div></section>}
  {tab==='year'&&<section className="mt-5 rounded-2xl border border-[#e7ddd3] bg-white p-5"><h2 className="text-xl font-bold">{year}년 현황</h2><div className="mt-5 grid gap-3">{yearRows.map(row=>{const max=Math.max(1,...yearRows.map(item=>Math.max(item.income,item.expense)));return <div key={row.month} className="grid grid-cols-[36px_1fr_auto] items-center gap-3"><b className="text-sm">{row.month}월</b><div className="grid gap-1"><div className="h-2 rounded-full bg-emerald-100"><div className="h-2 rounded-full bg-emerald-600" style={{width:`${row.income/max*100}%`}}/></div><div className="h-2 rounded-full bg-rose-100"><div className="h-2 rounded-full bg-rose-500" style={{width:`${row.expense/max*100}%`}}/></div></div><span className={`min-w-24 text-right text-sm font-bold ${row.net<0?'text-red-600':'text-zinc-700'}`}>{won(row.net)}</span></div>})}</div><div className="mt-5 flex gap-4 text-xs"><span className="text-emerald-700">● 수입</span><span className="text-rose-600">● 지출</span></div></section>}
  {tab==='overdue'&&<section className="mt-5 rounded-2xl border border-[#e7ddd3] bg-white p-5"><h2 className="text-xl font-bold">{Number(month.slice(5))}월 원비·미납 관리</h2><p className="mt-1 text-sm text-zinc-500">먼저 학생별 월 원비를 입력한 뒤 납부 여부를 관리하세요.</p><div className="mt-5 grid gap-3">{students.map(student=>{const enrollment=enrollments.find(item=>item.student_id===student.id);if(!enrollment)return null;const payment=payments.find(item=>item.student_id===student.id&&item.billing_month===monthDate);return <div key={student.id} className="flex flex-wrap items-center gap-3 rounded-xl border p-4"><b className="min-w-24 flex-1">{student.name}</b><label className="flex items-center gap-2 text-sm text-zinc-500">월 원비<input type="number" min="0" step="10000" defaultValue={enrollment.monthly_fee} onBlur={event=>void updateFee(enrollment,Number(event.target.value))} className="w-32 rounded-lg border px-3 py-2 text-right text-zinc-900"/></label><button disabled={saving||enrollment.monthly_fee<=0} onClick={()=>void togglePaid(student,enrollment,payment)} className={`rounded-lg px-4 py-2 text-sm font-bold disabled:opacity-40 ${payment?.paid?'bg-emerald-100 text-emerald-700':'bg-red-50 text-red-600'}`}>{payment?.paid?'납부 완료':'미납'}</button></div>})}{students.length===0&&<p className="py-8 text-center text-zinc-400">등록된 학생이 없습니다.</p>}</div></section>}
  </>}
  </div>{modal&&<Modal onClose={()=>setModal(false)}><form onSubmit={saveTransaction} className="grid gap-4"><div className="grid grid-cols-2 gap-3"><label className="grid gap-1 text-sm font-bold">날짜<input required type="date" value={form.transaction_date} onChange={event=>setForm({...form,transaction_date:event.target.value})} className="rounded-xl border px-3 py-3 font-normal"/></label><label className="grid gap-1 text-sm font-bold">구분<select value={form.transaction_type} onChange={event=>{const type=event.target.value as 'income'|'expense';setForm({...form,transaction_type:type,category:categoryOptions[type][0]})}} className="rounded-xl border bg-white px-3 py-3 font-normal"><option value="income">수입</option><option value="expense">지출</option></select></label></div><label className="grid gap-1 text-sm font-bold">항목<select value={form.category} onChange={event=>setForm({...form,category:event.target.value})} className="rounded-xl border bg-white px-3 py-3 font-normal">{categoryOptions[form.transaction_type].map(category=><option key={category}>{category}</option>)}</select></label><label className="grid gap-1 text-sm font-bold">내용<input required value={form.description} onChange={event=>setForm({...form,description:event.target.value})} placeholder="예: 7월 화구 재료 구입" className="rounded-xl border px-4 py-3 font-normal"/></label><div className="grid grid-cols-2 gap-3"><label className="grid gap-1 text-sm font-bold">결제 방법<select value={form.payment_method} onChange={event=>setForm({...form,payment_method:event.target.value})} className="rounded-xl border bg-white px-3 py-3 font-normal"><option value="card">카드</option><option value="cash">현금</option><option value="transfer">계좌이체</option><option value="other">기타</option></select></label><label className="grid gap-1 text-sm font-bold">금액<input required type="number" min="1" value={form.amount} onChange={event=>setForm({...form,amount:event.target.value})} className="rounded-xl border px-4 py-3 text-right font-normal"/></label></div><button disabled={saving} className="rounded-xl bg-rose-700 py-4 font-bold text-white">{saving?'저장 중...':'저장'}</button></form></Modal>}</main>
}
