import Anthropic from "@anthropic-ai/sdk";
import { createClient } from "@supabase/supabase-js";

export const runtime="nodejs";
const anthropic=new Anthropic({apiKey:process.env.ANTHROPIC_API_KEY!});
const MODEL=process.env.ANTHROPIC_MODEL||"claude-opus-4-8";
const allowed=new Set(["image/jpeg","image/png","image/webp"]);
const schema={type:"object",properties:{lowenfeld_stage:{type:"string"},stage_comparison:{type:"string"},expressive_tendencies:{type:"string"},body_form_expression:{type:"string"},color_pattern_materials:{type:"string"},composition_space:{type:"string"},visible_strengths:{type:"string"},growth_points:{type:"string"},parent_summary:{type:"string"},caution_note:{type:"string"}},required:["lowenfeld_stage","stage_comparison","expressive_tendencies","body_form_expression","color_pattern_materials","composition_space","visible_strengths","growth_points","parent_summary","caution_note"],additionalProperties:false};
const stages=`로웬펠드 발달 단계 참고: 난화기(약 2~4세), 전도식기(약 4~7세), 도식기(약 7~9세), 또래집단기/여명기(약 9~12세), 의사실기(약 12~14세), 결정기(약 14~17세). 연령 경계는 개인과 환경에 따라 달라지므로 절대 평가하지 않는다.`;
function extractJson(text:string){const fenced=text.match(/```(?:json)?\s*([\s\S]*?)```/i);if(fenced)return fenced[1].trim();const start=text.indexOf("{");const end=text.lastIndexOf("}");return start>=0&&end>start?text.slice(start,end+1):text}
export async function POST(request:Request){try{const token=request.headers.get("authorization")?.replace(/^Bearer\s+/i,"");if(!token)return Response.json({error:"로그인이 필요합니다."},{status:401});const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!);const {data:{user}}=await supabase.auth.getUser(token);if(!user)return Response.json({error:"로그인이 만료되었습니다."},{status:401});const form=await request.formData();const image=form.get("image");const studentName=String(form.get("studentName")||"");const age=Number(form.get("age"));const title=String(form.get("title")||"");const context=String(form.get("context")||"");if(!(image instanceof File)||!studentName||!age)return Response.json({error:"학생, 나이, 그림을 모두 입력해주세요."},{status:400});if(image.size>10*1024*1024)return Response.json({error:"그림 파일은 10MB 이하로 올려주세요."},{status:400});if(!allowed.has(image.type))return Response.json({error:"JPG, PNG, WEBP 그림만 올릴 수 있습니다."},{status:400});const data=Buffer.from(await image.arrayBuffer()).toString("base64");const message=await anthropic.messages.create({model:MODEL,max_tokens:3200,system:`당신은 아동 미술교육 관찰 기록을 돕는 보조 AI입니다. ${stages} 사진에 실제로 보이는 특징과 교사가 제공한 맥락만 사용하세요. 성격, 지능, 애착, 정서 안정, 장애, 가족관계 또는 심리 상태를 진단하거나 단정하지 마세요. 성별 고정관념이나 남아·여아 평균 비교를 사용하지 마세요. expressive_tendencies는 성격이 아니라 선호하는 구도, 선, 색, 반복, 세부 묘사 같은 시각적 표현 경향만 적으세요. 발달 단계는 연령에 따른 참고 단계와 작품에서 관찰되는 특징을 함께 설명하되 우열이나 지연으로 낙인찍지 마세요. 각 항목은 구체적이고 따뜻한 한국어 2~4문장으로 작성하세요. parent_summary는 상담에 바로 사용할 5~7문장으로 작성하세요. caution_note에는 반드시 '미술교육 관찰 기록이며 그림 한 장으로 성격이나 심리 상태를 진단하지 않는다'는 뜻을 포함하세요. Return only valid JSON with this JSON Schema: ${JSON.stringify(schema)}`,messages:[{role:"user",content:[{type:"image",source:{type:"base64",media_type:image.type as "image/jpeg"|"image/png"|"image/webp",data}},{type:"text",text:[`학생: ${studentName}`,`만 나이: ${age}세`,`작품 제목 또는 주제: ${title||"입력 없음"}`,`선생님 관찰 맥락: ${context||"입력 없음"}`,"다음 항목을 분석하세요: 로웬펠드 단계 비교, 표현 경향, 신체·형태, 색채·패턴·재료, 화면 구성·공간, 강점, 다음 수업 성장 포인트, 학부모 상담 요약."].join("\n")}]}]});const block=message.content.find(item=>item.type==="text");if(!block||block.type!=="text")throw new Error("No response");return Response.json(JSON.parse(extractJson(block.text)))}catch(error){console.error("artwork analysis failed",error);return Response.json({error:"그림 분석 중 오류가 발생했습니다. 잠시 후 다시 시도해주세요."},{status:500})}}
