"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { supabase } from "@/lib/supabase";

type Student={id:string;name:string;school_name:string|null};
type Feedback={id:string;student_id:string;feedback_date:string;lesson_topic:string;observation_notes:string;class_summary:string;strengths:string;next_focus:string;parent_message:string;status:"draft"|"shared";created_at:string};
type Result={class_summary:string;strengths:string;next_focus:string;parent_message:string};
const isoToday=()=>new Date().toLocaleDateString("sv-SE");

export default function FeedbackPage(){
  const [students,setStudents]=useState<Student[]>([]);const [history,setHistory]=useState<Feedback[]>([]);const [studentId,setStudentId]=useState("");
  const [date,setDate]=useState(isoToday());const [lessonTopic,setLessonTopic]=useState("");const [observations,setObservations]=useState("");const [mood,setMood]=useState("");const [challenge,setChallenge]=useState("");const [nextPlan,setNextPlan]=useState("");
  const [result,setResult]=useState<Result|null>(null);const [loading,setLoading]=useState(true);const [generating,setGenerating]=useState(false);const [saving,setSaving]=useState(false);const [error,setError]=useState("");const [notice,setNotice]=useState("");const [search,setSearch]=useState("");
  const load=useCallback(async()=>{setLoading(true);const [studentResult,feedbackResult]=await Promise.all([supabase.from("students").select("id,name,school_name").eq("active",true).order("name"),supabase.from("student_feedback").select("*").order("feedback_date",{ascending:false}).limit(100)]);if(studentResult.error||feedbackResult.error)setError(feedbackResult.error?.code==="PGRST205"?"학생 피드백 데이터베이스 설정이 필요합니다.":studentResult.error?.message||feedbackResult.error?.message||"불러오기 오류");else{setStudents(studentResult.data as Student[]);setHistory(feedbackResult.data as Feedback[])}setLoading(false)},[]);
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[load]);
  useEffect(()=>{if(studentId||students.length===0)return;const requested=new URLSearchParams(window.location.search).get("student");if(!requested||!students.some(student=>student.id===requested))return;const timer=window.setTimeout(()=>setStudentId(requested),0);return()=>window.clearTimeout(timer)},[studentId,students]);
  const selected=students.find(student=>student.id===studentId);const visibleHistory=useMemo(()=>history.filter(item=>{const student=students.find(value=>value.id===item.student_id);return (!studentId||item.student_id===studentId)&&(!search||[student?.name,item.lesson_topic,item.parent_message].filter(Boolean).some(value=>value!.toLowerCase().includes(search.toLowerCase())))}),[history,search,studentId,students]);
  const flash=(message:string)=>{setNotice(message);window.setTimeout(()=>setNotice(""),2500)};
  const generate=async(event:FormEvent)=>{event.preventDefault();if(!selected)return setError("학생을 선택해주세요.");setGenerating(true);setError("");const {data:{session}}=await supabase.auth.getSession();try{const response=await fetch("/api/feedback/generate",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${session?.access_token??""}`},body:JSON.stringify({studentName:selected.name,lessonTopic,observations,mood,challenge,nextPlan})});const data=await response.json();if(!response.ok)throw new Error(data.error);setResult(data as Result)}catch(err){setError(err instanceof Error?err.message:"피드백을 만들지 못했습니다.")}finally{setGenerating(false)}};
  const save=async()=>{if(!result||!studentId)return;setSaving(true);const {error:saveError}=await supabase.from("student_feedback").insert({student_id:studentId,feedback_date:date,lesson_topic:lessonTopic,observation_notes:observations,...result,status:"draft"});setSaving(false);if(saveError)return setError(saveError.message);flash("피드백을 저장했습니다.");setResult(null);setLessonTopic("");setObservations("");setMood("");setChallenge("");setNextPlan("");await load()};
  const copy=async(text:string)=>{await navigator.clipboard.writeText(text);flash("학부모용 피드백을 복사했습니다.")};
  const markShared=async(item:Feedback)=>{const status=item.status==="shared"?"draft":"shared";const {error:updateError}=await supabase.from("student_feedback").update({status}).eq("id",item.id);if(updateError)return setError(updateError.message);setHistory(current=>current.map(value=>value.id===item.id?{...value,status}:value));flash(status==="shared"?"전달 완료로 표시했습니다.":"초안으로 되돌렸습니다.")};
  return <main className="min-h-screen flex-1 bg-amber-50/40 px-3 py-6 sm:px-6"><div className="mx-auto max-w-6xl"><header><p className="text-sm font-bold tracking-[.2em] text-violet-600">STUDENT FEEDBACK</p><h1 className="mt-2 text-3xl font-bold">학생 피드백</h1><p className="mt-2 text-sm text-zinc-500">수업 관찰을 바탕으로 학부모에게 전달할 피드백을 만들고 기록합니다.</p></header>{notice&&<div className="mt-4 rounded-xl bg-emerald-600 px-4 py-3 text-sm font-bold text-white">{notice}</div>}{error&&<div className="mt-4 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}
  {loading?<div className="mt-6 rounded-2xl bg-white p-12 text-center">불러오는 중...</div>:<div className="mt-6 grid gap-5 lg:grid-cols-[1fr_.9fr]"><section className="rounded-3xl bg-white p-5 shadow-sm ring-1 ring-amber-100 sm:p-7"><h2 className="text-xl font-bold">오늘 수업 기록</h2><form onSubmit={generate} className="mt-5 grid gap-4"><div className="grid gap-3 sm:grid-cols-2"><label className="grid gap-1 text-sm font-bold">학생<select required value={studentId} onChange={event=>setStudentId(event.target.value)} className="rounded-xl border bg-white px-4 py-3 font-normal"><option value="">선택하세요</option>{students.map(student=><option key={student.id} value={student.id}>{student.name}{student.school_name?` · ${student.school_name}`:""}</option>)}</select></label><label className="grid gap-1 text-sm font-bold">수업 날짜<input type="date" value={date} onChange={event=>setDate(event.target.value)} className="rounded-xl border px-4 py-3 font-normal"/></label></div><label className="grid gap-1 text-sm font-bold">수업 주제<input required value={lessonTopic} onChange={event=>setLessonTopic(event.target.value)} placeholder="예: 수채화로 여름 바다 표현하기" className="rounded-xl border px-4 py-3 font-normal"/></label><label className="grid gap-1 text-sm font-bold">선생님 관찰 메모<textarea required rows={4} value={observations} onChange={event=>setObservations(event.target.value)} placeholder="학생이 직접 선택한 색, 집중한 활동, 새롭게 시도한 점을 적어주세요." className="rounded-xl border px-4 py-3 font-normal"/></label><div className="grid gap-3 sm:grid-cols-2"><label className="grid gap-1 text-sm font-bold">수업 태도·기분<input value={mood} onChange={event=>setMood(event.target.value)} placeholder="예: 즐겁게 집중함" className="rounded-xl border px-4 py-3 font-normal"/></label><label className="grid gap-1 text-sm font-bold">어려워한 점<input value={challenge} onChange={event=>setChallenge(event.target.value)} placeholder="없으면 비워두세요" className="rounded-xl border px-4 py-3 font-normal"/></label></div><label className="grid gap-1 text-sm font-bold">다음 수업 계획<input value={nextPlan} onChange={event=>setNextPlan(event.target.value)} placeholder="예: 색 혼합을 한 번 더 연습" className="rounded-xl border px-4 py-3 font-normal"/></label><button disabled={generating} className="rounded-xl bg-violet-600 py-4 font-bold text-white disabled:opacity-50">{generating?"AI가 작성 중...":"AI 피드백 만들기"}</button></form>
  {result&&<div className="mt-6 grid gap-4 border-t pt-6"><h3 className="text-lg font-bold">생성된 피드백 <span className="text-xs font-normal text-zinc-400">저장 전 수정할 수 있습니다</span></h3>{([['class_summary','수업 요약'],['strengths','관찰된 강점'],['next_focus','다음 지도 방향'],['parent_message','학부모 전달 문구']] as [keyof Result,string][]).map(([key,label])=><label key={key} className="grid gap-1 text-sm font-bold">{label}<textarea rows={key==='parent_message'?6:3} value={result[key]} onChange={event=>setResult({...result,[key]:event.target.value})} className="rounded-xl border px-4 py-3 font-normal leading-6"/></label>)}<div className="grid grid-cols-2 gap-3"><button type="button" onClick={()=>void copy(result.parent_message)} className="rounded-xl border py-3 font-bold">먼저 복사</button><button type="button" disabled={saving} onClick={()=>void save()} className="rounded-xl bg-zinc-900 py-3 font-bold text-white">{saving?"저장 중...":"피드백 저장"}</button></div></div>}</section>
  <section><div className="rounded-3xl bg-white p-5 shadow-sm ring-1 ring-amber-100"><h2 className="text-xl font-bold">피드백 기록</h2><input value={search} onChange={event=>setSearch(event.target.value)} placeholder="학생 이름·수업 주제 검색" className="mt-4 w-full rounded-xl border px-4 py-3"/><div className="mt-4 grid gap-3">{visibleHistory.map(item=>{const student=students.find(value=>value.id===item.student_id);return <article key={item.id} className="rounded-2xl border p-4"><div className="flex items-start justify-between gap-3"><div><b>{student?.name||"학생"}</b><p className="mt-1 text-xs text-zinc-400">{item.feedback_date} · {item.lesson_topic}</p></div><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${item.status==='shared'?'bg-emerald-100 text-emerald-700':'bg-zinc-100 text-zinc-500'}`}>{item.status==='shared'?'전달 완료':'초안'}</span></div><p className="mt-3 whitespace-pre-wrap text-sm leading-6 text-zinc-600">{item.parent_message}</p><div className="mt-3 flex justify-end gap-3 border-t pt-3"><button onClick={()=>void copy(item.parent_message)} className="text-xs font-bold text-violet-600">복사</button><button onClick={()=>void markShared(item)} className="text-xs font-bold text-emerald-700">{item.status==='shared'?'초안으로':'전달 완료'}</button></div></article>})}{visibleHistory.length===0&&<p className="rounded-xl bg-zinc-50 p-8 text-center text-sm text-zinc-400">저장된 피드백이 없습니다.</p>}</div></div></section></div>}</div></main>
}
