"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { supabase } from "@/lib/supabase";

type Student={id:string;name:string;birth_date:string|null;school_name:string|null;guardian_name:string|null;guardian_phone:string|null;notes:string|null};
type ClassRow={id:string;name:string;day_of_week:number;start_time:string;end_time:string;teacher_name:string|null};
type Enrollment={student_id:string;class_id:string;duration_minutes:number;vehicle_mode:string;monthly_fee:number};
type Transaction={transaction_date:string;transaction_type:"income"|"expense";category:string;description:string;payment_method:string;amount:number};
type Payment={student_id:string;billing_month:string;amount:number;paid:boolean;paid_at:string|null};
type Feedback={student_id:string;feedback_date:string;lesson_topic:string;class_summary:string;strengths:string;next_focus:string;parent_message:string;status:string};
const DAYS=["월","화","수","목","금","토"];
const now=new Date();const currentMonth=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,"0")}`;
const xml=(value:unknown)=>String(value??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");
const html=(value:unknown)=>String(value??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#39;");
const saveBlob=(content:BlobPart,type:string,name:string)=>{const url=URL.createObjectURL(new Blob([content],{type}));const link=document.createElement("a");link.href=url;link.download=name;link.click();window.setTimeout(()=>URL.revokeObjectURL(url),500)};
const excelCell=(value:unknown,number=false)=>`<Cell><Data ss:Type="${number?"Number":"String"}">${xml(value)}</Data></Cell>`;
const excelFile=(title:string,headers:string[],rows:(string|number|null)[][])=>`<?xml version="1.0"?><Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"><Styles><Style ss:ID="Header"><Font ss:Bold="1" ss:Color="#FFFFFF"/><Interior ss:Color="#047857" ss:Pattern="Solid"/><Alignment ss:Vertical="Center"/></Style><Style ss:ID="Money"><NumberFormat ss:Format="#,##0"/></Style></Styles><Worksheet ss:Name="${xml(title.slice(0,28))}"><Table><Row ss:Height="28">${headers.map(h=>`<Cell ss:StyleID="Header"><Data ss:Type="String">${xml(h)}</Data></Cell>`).join("")}</Row>${rows.map(row=>`<Row>${row.map(value=>excelCell(value,typeof value==="number")).join("")}</Row>`).join("")}</Table><WorksheetOptions xmlns="urn:schemas-microsoft-com:office:excel"><FreezePanes/><FrozenNoSplit/><SplitHorizontal>1</SplitHorizontal><TopRowBottomPane>1</TopRowBottomPane></WorksheetOptions></Worksheet></Workbook>`;
const vehicleLabel:Record<string,string>={none:"없음",pickup:"승차",dropoff:"하차",both:"승하차"};
const paymentLabel:Record<string,string>={card:"카드",cash:"현금",transfer:"계좌이체",other:"기타"};

export default function DownloadsPage(){
  const [month,setMonth]=useState(currentMonth);const [students,setStudents]=useState<Student[]>([]);const [classes,setClasses]=useState<ClassRow[]>([]);const [enrollments,setEnrollments]=useState<Enrollment[]>([]);const [transactions,setTransactions]=useState<Transaction[]>([]);const [payments,setPayments]=useState<Payment[]>([]);const [feedback,setFeedback]=useState<Feedback[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [notice,setNotice]=useState("");
  const load=useCallback(async()=>{setLoading(true);setError("");const results=await Promise.all([supabase.from("students").select("id,name,birth_date,school_name,guardian_name,guardian_phone,notes").eq("active",true).order("name"),supabase.from("classes").select("id,name,day_of_week,start_time,end_time,teacher_name").eq("active",true).order("day_of_week").order("start_time"),supabase.from("class_enrollments").select("student_id,class_id,duration_minutes,vehicle_mode,monthly_fee"),supabase.from("finance_transactions").select("transaction_date,transaction_type,category,description,payment_method,amount").order("transaction_date"),supabase.from("tuition_payments").select("student_id,billing_month,amount,paid,paid_at").order("billing_month"),supabase.from("student_feedback").select("student_id,feedback_date,lesson_topic,class_summary,strengths,next_focus,parent_message,status").order("feedback_date")]);const failed=results.find(item=>item.error)?.error;if(failed)setError(failed.message);else{setStudents(results[0].data as Student[]);setClasses(results[1].data as ClassRow[]);setEnrollments(results[2].data as Enrollment[]);setTransactions(results[3].data as Transaction[]);setPayments(results[4].data as Payment[]);setFeedback(results[5].data as Feedback[])}setLoading(false)},[]);
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[load]);
  const flash=(message:string)=>{setNotice(message);window.setTimeout(()=>setNotice(""),2200)};
  const studentName=(id:string)=>students.find(item=>item.id===id)?.name||"학생";const classFor=(id:string)=>classes.find(item=>item.id===id);const enrollmentFor=(id:string)=>enrollments.find(item=>item.student_id===id);
  const monthTransactions=useMemo(()=>transactions.filter(item=>item.transaction_date.startsWith(month)),[month,transactions]);const monthPayments=useMemo(()=>payments.filter(item=>item.billing_month===`${month}-01`&&item.paid),[month,payments]);const monthFeedback=useMemo(()=>feedback.filter(item=>item.feedback_date.startsWith(month)),[feedback,month]);
  const downloadStudents=()=>{const rows=students.map(student=>{const enrollment=enrollmentFor(student.id),classRow=classFor(enrollment?.class_id||"");return [student.name,student.birth_date,student.school_name,student.guardian_name,student.guardian_phone,classRow?`${DAYS[classRow.day_of_week-1]} ${classRow.start_time.slice(0,5)} ${classRow.name}`:"",enrollment?.duration_minutes?`${enrollment.duration_minutes}분` :"",vehicleLabel[enrollment?.vehicle_mode||"none"]||"없음",enrollment?.monthly_fee||0,student.notes]});saveBlob(excelFile("학생 명단",["학생 이름","생년월일","학교·유치원","학부모","연락처","수업반","수업 시간","차량","월 원비","메모"],rows),"application/vnd.ms-excel;charset=utf-8","코코미술_학생명단.xls");flash("학생 명단을 저장했습니다.")};
  const downloadFinance=()=>{const tuitionRows=monthPayments.map(item=>[month,"수입","원비",`${studentName(item.student_id)} 원비`,"원비 납부",item.amount]);const txRows=monthTransactions.map(item=>[item.transaction_date,item.transaction_type==="income"?"수입":"지출",item.category,item.description,paymentLabel[item.payment_method]||item.payment_method,item.amount]);saveBlob(excelFile(`${month} 재무 장부`,["날짜","구분","분류","내용","결제 방법","금액"],[...tuitionRows,...txRows]),"application/vnd.ms-excel;charset=utf-8",`코코미술_${month}_재무장부.xls`);flash("재무 장부를 저장했습니다.")};
  const buildScheduleCanvas=()=>{const canvas=document.createElement("canvas");canvas.width=1800;canvas.height=1150;const ctx=canvas.getContext("2d");if(!ctx)throw new Error("이미지를 만들 수 없습니다.");ctx.fillStyle="#fffdf8";ctx.fillRect(0,0,canvas.width,canvas.height);ctx.strokeStyle="#d1d5db";ctx.lineWidth=2;ctx.fillStyle="#111827";ctx.font="bold 52px sans-serif";ctx.fillText("코코미술 수업 시간표",60,78);ctx.font="24px sans-serif";ctx.fillStyle="#6b7280";ctx.fillText("60분 검정 · 90분 파랑 · 120분 초록 · 차량 이용 주황",60,120);const left=55,top=155,col=(canvas.width-left*2)/6;DAYS.forEach((day,index)=>{ctx.fillStyle=["#fef08a","#fef08a","#bae6fd","#bae6fd","#fecaca","#d9f99d"][index];ctx.fillRect(left+index*col,top,col,58);ctx.strokeRect(left+index*col,top,col,58);ctx.fillStyle="#111827";ctx.font="bold 27px sans-serif";ctx.textAlign="center";ctx.fillText(`${day}요일`,left+index*col+col/2,top+38)});ctx.textAlign="left";DAYS.forEach((_,dayIndex)=>{const dayClasses=classes.filter(item=>item.day_of_week===dayIndex+1);let y=top+58;dayClasses.forEach(classRow=>{const members=enrollments.filter(item=>item.class_id===classRow.id);const height=Math.max(100,62+Math.ceil(Math.max(1,members.length)/2)*30);ctx.fillStyle="#ffffff";ctx.fillRect(left+dayIndex*col,y,col,height);ctx.strokeStyle="#d1d5db";ctx.strokeRect(left+dayIndex*col,y,col,height);ctx.fillStyle="#065f46";ctx.font="bold 22px sans-serif";ctx.fillText(`${classRow.start_time.slice(0,5)} ${classRow.name}`,left+dayIndex*col+12,y+29);members.forEach((en,index)=>{const student=students.find(item=>item.id===en.student_id);if(!student)return;ctx.fillStyle=en.vehicle_mode!=="none"?"#ea580c":en.duration_minutes===90?"#1d4ed8":en.duration_minutes===120?"#15803d":"#18181b";ctx.font="19px sans-serif";ctx.fillText(student.name,left+dayIndex*col+12+(index%2)*(col/2),y+60+Math.floor(index/2)*30)});y+=height})});return canvas};
  const downloadScheduleImage=()=>{const canvas=buildScheduleCanvas();canvas.toBlob(blob=>{if(blob)saveBlob(blob,"image/png","코코미술_전체시간표.png")},"image/png");flash("시간표 이미지를 저장했습니다.")};
  const printSchedule=()=>{const data=buildScheduleCanvas().toDataURL("image/png");const popup=window.open("","_blank","width=1100,height=800");if(!popup)return setError("인쇄 창이 차단되었습니다. 팝업을 허용해주세요.");popup.document.write(`<title>코코미술 시간표</title><style>@page{size:A4 landscape;margin:8mm}body{margin:0}img{width:100%;height:auto}</style><img src="${data}" onload="window.print()">`);popup.document.close()};
  const printFeedbackPdf=()=>{if(!monthFeedback.length)return setError("선택한 달에 저장된 피드백이 없습니다.");const popup=window.open("","_blank","width=900,height=800");if(!popup)return setError("PDF 저장 창이 차단되었습니다. 팝업을 허용해주세요.");const cards=monthFeedback.map(item=>`<article><header><b>${html(studentName(item.student_id))}</b><span>${html(item.feedback_date)} · ${html(item.lesson_topic)}</span></header><h3>수업 요약</h3><p>${html(item.class_summary)}</p><h3>관찰된 강점</h3><p>${html(item.strengths)}</p><h3>다음 지도 방향</h3><p>${html(item.next_focus)}</p><div class="message"><b>학부모 전달 내용</b><p>${html(item.parent_message)}</p></div></article>`).join("");popup.document.write(`<title>코코미술 ${html(month)} 피드백</title><style>@page{size:A4;margin:14mm}body{font-family:Arial,'Malgun Gothic',sans-serif;color:#27272a}h1{color:#6d28d9}article{break-inside:avoid;border:1px solid #ddd;border-radius:14px;padding:18px;margin:0 0 18px}header{display:flex;justify-content:space-between;border-bottom:2px solid #ede9fe;padding-bottom:10px}header b{font-size:20px}header span{font-size:12px;color:#777}h3{font-size:13px;color:#6d28d9;margin:15px 0 4px}p{white-space:pre-wrap;line-height:1.65;margin:0}.message{background:#f5f3ff;padding:12px;border-radius:10px;margin-top:14px}.message b{color:#5b21b6}</style><h1>코코미술 ${html(month)} 학생 피드백</h1>${cards}<script>window.onload=()=>window.print()<\/script>`);popup.document.close()};
  const cards=[{icon:"👧",title:"학생 명단 엑셀 저장",description:`현재 학생 ${students.length}명의 연락처·수업반·차량·원비를 저장합니다.`,action:downloadStudents,button:"학생 명단 저장",color:"emerald"},{icon:"💰",title:"재무 장부 엑셀 저장",description:`${month} 수입·지출과 원비 납부 내역을 저장합니다.`,action:downloadFinance,button:"재무 장부 저장",color:"rose"},{icon:"🗓️",title:"시간표 이미지·인쇄",description:"전체 수업반과 학생 명단을 한 페이지 시간표로 만듭니다.",action:downloadScheduleImage,button:"PNG 이미지 저장",color:"sky"},{icon:"💬",title:"피드백 기록 PDF 저장",description:`${month} 피드백 ${monthFeedback.length}건을 보기 좋은 문서로 저장합니다.`,action:printFeedbackPdf,button:"PDF 저장·인쇄",color:"violet"}] as const;
  return <main className="min-h-screen flex-1 bg-zinc-50 px-3 py-6 sm:px-6"><div className="mx-auto max-w-5xl"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-bold tracking-[.2em] text-emerald-600">DOWNLOAD CENTER</p><h1 className="mt-1 text-3xl font-black">자료 내려받기</h1><p className="mt-2 text-sm text-zinc-500">필요한 학원 자료를 엑셀, 이미지, PDF로 저장합니다.</p></div><input type="month" value={month} onChange={event=>setMonth(event.target.value)} className="rounded-xl border bg-white px-4 py-3 font-bold"/></header>{notice&&<div className="mt-4 rounded-xl bg-emerald-600 px-4 py-3 text-sm font-bold text-white">{notice}</div>}{error&&<div className="mt-4 flex justify-between rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700"><span>{error}</span><button onClick={()=>setError("")}>×</button></div>}{loading?<div className="mt-6 rounded-3xl bg-white p-16 text-center">자료를 준비하는 중...</div>:<div className="mt-6 grid gap-4 sm:grid-cols-2">{cards.map(card=><section key={card.title} className="rounded-3xl bg-white p-6 shadow-sm ring-1 ring-zinc-100"><div className="text-4xl">{card.icon}</div><h2 className="mt-4 text-xl font-black">{card.title}</h2><p className="mt-2 min-h-12 text-sm leading-6 text-zinc-500">{card.description}</p><button onClick={card.action} className={`mt-5 w-full rounded-xl py-3.5 font-bold text-white ${card.color==="emerald"?"bg-emerald-600":card.color==="rose"?"bg-rose-600":card.color==="sky"?"bg-sky-600":"bg-violet-600"}`}>{card.button}</button>{card.title.startsWith("시간표")&&<button onClick={printSchedule} className="mt-2 w-full rounded-xl border py-3 font-bold">시간표 바로 인쇄</button>}</section>)}</div>}<div className="mt-5 rounded-2xl bg-amber-50 p-4 text-sm leading-6 text-amber-800"><b>PDF 저장 방법:</b> 피드백 버튼을 누른 뒤 인쇄 화면에서 프린터를 <b>PDF로 저장</b>으로 선택하세요.</div></div></main>;
}
